/** AUTH **/
export const LOGIN_ATTEMP = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGIN_ATTEMP_FACEBOOK = 'LOGIN_ATTEMPT_FACEBOOK';
export const LOGIN_ATTEMP_GOOGLE = 'LOGIN_ATTEMP_GOOGLE';
export const LOGIN_ATTEMP_TWITTER = 'LOGIN_ATTEMP_TWITTER';

export const REGISTER_ATTEMP = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

/** USER **/
export const USER_READ = 'USER_READ';
export const USER_READ_SUCCESS = 'USER_READ_SUCCESS';
export const USER_READ_FAILURE = 'USER_READ_FAILURE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR= 'USER_UPDATE_ERROR';

/** IMAGE UPLOAD AND IMAGE FILE READ **/
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';
export const IMAGE_UPLOAD_PROGRESS = 'IMAGE_UPLOAD_FAILURE';

export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';

export const IMAGE_READ = 'IMAGE_READ';
export const IMAGE_READ_PROGRESS = 'IMAGE_READ_FAILURE';
export const IMAGE_READ_FAILURE = 'IMAGE_READ_FAILURE';
export const IMAGE_READ_SUCCESS = 'IMAGE_READ_SUCCESS';
